- pom.xml
Updated Aikau to the new released version which contains copyright info updates.
> Aikau version update

- packaging/installer/pom.xml
> Share installer added

- packaging/distribution/src/main/resources/web-extension-samples/custom-slingshot-application-context.xml.sample
- packaging/docker/src/main/resources/web-extension-samples/custom-slingshot-application-context.xml.sample
- share/pom.xml
- share/src/main/resources/alfresco/web-extension/custom-slingshot-application-context.xml.sample
* Fix XSD to the https URLs in samples
* Revert back the version of hazelcast-spring to 2.4
> SHA-2191 Fix Clustering

- alfresco-enterprise/pom.xml
- pom.xml
Version update:
- alfresco content services
- alfresco platform services
> Update Alfresco content services version

- pom.xml
* Remove -SNAPSHOT from alfresco.platform.version
> REPO-3637: Update pom

- pom.xml
Added commons-lang version 2.6
> Fix:MNT-19906 commons-lang version update

- web-framework-commons/src/main/resources/alfresco/site-webscripts/org/alfresco/components/form/controls/date.ftl
Small change/fix to date.ftl for MNT-18099
> MNT-18099 - fix to date.ftl

- share-services/src/main/resources/alfresco/templates/webscripts/org/alfresco/slingshot/documentlibrary/action/files.delete.json.js
Fixed the issue on files/folders and their links deletion by ordering them, so the links will be deleted before the actual files/folders.
> MNT-19519: Fixed the issue on files/folders and their links deletion

- share/src/main/resources/alfresco/share-documentlibrary-config.xml
- share/src/main/resources/alfresco/site-webscripts/org/alfresco/share/pages/faceted-search/faceted-search.get.js
Wired in manage aspects widget introduced in https://issues.alfresco.com/jira/browse/AKU-396 in order to fix this issue.
> MNT-16608 - wired in manage-aspects widgets

- share/src/main/webapp/themes/hcBlack/presentation.css
Small change to high-contrast theme for better visibility in datalist picker container.
See investigation notes here https://issues.alfresco.com/jira/browse/MNT-19173?focusedCommentId=598210&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-598210
> MNT-19173 - change HC theme slightly for better visibility

- share/src/main/webapp/components/document-details/document-versions.js
Please see https://issues.alfresco.com/jira/browse/MNT-20325?focusedCommentId=602477&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-602477 for details.
> MNT-20325 - encoding document name for document version markup

- web-framework-commons/src/main/resources/alfresco/site-webscripts/org/alfresco/components/form/form.get_de.properties
- web-framework-commons/src/main/resources/alfresco/site-webscripts/org/alfresco/components/form/form.get_es.properties
- web-framework-commons/src/main/resources/alfresco/site-webscripts/org/alfresco/components/form/form.get_fr.properties
- web-framework-commons/src/main/resources/alfresco/site-webscripts/org/alfresco/components/form/form.get_it.properties
- web-framework-commons/src/main/resources/alfresco/site-webscripts/org/alfresco/components/form/form.get_ja.properties
- web-framework-commons/src/main/resources/alfresco/site-webscripts/org/alfresco/components/form/form.get_nb.properties
- web-framework-commons/src/main/resources/alfresco/site-webscripts/org/alfresco/components/form/form.get_nl.properties
- web-framework-commons/src/main/resources/alfresco/site-webscripts/org/alfresco/components/form/form.get_pt_BR.properties
- web-framework-commons/src/main/resources/alfresco/site-webscripts/org/alfresco/components/form/form.get_ru.properties
- web-framework-commons/src/main/resources/alfresco/site-webscripts/org/alfresco/components/form/form.get_zh_CN.properties
Changes made to the date field property as per this comment https://issues.alfresco.com/jira/browse/SHA-2177?focusedCommentId=603143&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-603143
> SHA-2177 - changed date formats as per recommendations for date field

- share/src/main/webapp/modules/simple-dialog.js
Pls see comment https://issues.alfresco.com/jira/browse/MNT-19397?focusedCommentId=603755&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-603755
> MNT-19397 - modified simple-dialog to disable submit button on initial click

- share/src/main/java/org/alfresco/web/scripts/SlingshotRemoteClient.java
Please see Jira comment https://issues.alfresco.com/jira/browse/MNT-18730?focusedCommentId=604191&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-604191 for investigation
> MNT-18730 Omit UTF16 XML files from binary check

- cmm-qa/pom.xml
- pom.xml
- share-services/pom.xml
- share/pom.xml
- share/src/main/java/org/alfresco/web/cmm/CMMService.java
- share/src/main/java/org/alfresco/web/cmm/CMMServicePost.java
- share/src/main/java/org/alfresco/web/config/header/HeaderItemsElementReader.java
- wcmquickstart-module/wcmquickstartwebsite/pom.xml
- web-editor-plugin/pom.xml
- web-editor-samples/customer-site/pom.xml
- web-editor/pom.xml
- web-framework-commons/pom.xml
- web-framework-commons/src/main/java/org/alfresco/web/config/forms/DependenciesElementReader.java
- web-framework-commons/src/main/java/org/alfresco/web/config/forms/FormElementReader.java
Please see ACE-5894 for investigation, specifically https://issues.alfresco.com/jira/browse/ACE-5894?focusedCommentId=605183&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-605183
> ACE-5894 excluded old transitive dom4j dependency, brought in updated version and fixed compilation issues

- web-framework-commons/src/main/webapp/components/object-finder/object-finder.js
- Fix in Share side for the tags issue
> SHA-2200 : CLONE MNT-17231 - When a tag newly created is added the tags are not updated in the edit form

- pom.xml
- share/pom.xml
> SHA-2297 (REPO-4245) Build plans for Corretto JDK8 on ACS 5.2.N

- packaging/docker-aws/pom.xml
Once merged, this change will be cherry-picked into:
* **support/SP/6.1.N**
* **master**
> ATS-380 : Update AI amp version to 1.0.0

- share/src/main/webapp/components/rules/rule-details.css
- share/src/main/webapp/components/rules/rule-edit.css
Please review css changes for word wrapping in folder Rules (working with Alex Strachan)
> MNT-17551 fixed styling for rule word wrapping

- share/src/main/webapp/components/rules/rule-details.css
> MNT-20634 fixed styling for rule description word wrapping FF/Chrome/IE11

- share-services/src/main/resources/alfresco/templates/webscripts/org/alfresco/slingshot/search/live-search.lib.js
- share-services/src/main/resources/alfresco/templates/webscripts/org/alfresco/slingshot/search/search.lib.js
Fixed filter query. The query on user is case sensitive.
> [SEARCH-1716]

- cmm-qa/pom.xml
- pom.xml
- share-services/pom.xml
- share-services/src/main/java/org/alfresco/repo/web/scripts/datalist/DataListDownloadWebScript.java
- share/src/main/resources/web-application-config.xml
- wcmquickstart-module/wcmquickstartmodule/pom.xml
- wcmquickstart-module/wcmquickstartmodule/src/main/amp/config/alfresco/module/org_alfresco_module_wcmquickstart/benchmark/website-generator-context.xml
- web-framework-commons/pom.xml
- Upgraded Spring and a few other dependencies
- Small changes to address Spring 5
> SHA-2277 : Share changes for Spring 5 support

- packaging/docker-aws/pom.xml
Once this PR is merged we'll also cherry-pick the commit into the `support/SP/6.2.N` branch.
> ATS-571: Release Intelligence Services (AIS) 1.1.0-RC3

- packaging/docker-aws/pom.xml
Once reviewed & merged, this commit will  be cherry-picked into the **support/SP/6.2.N** branch.
> ATS-516: Release Intelligence Services (AIS) 1.1.0

- web-framework-commons/src/main/webapp/js/alfresco.js
- add also the first entity from path ("Sites" or first folder) to the path sent to backend services
> MNT-20871: Edit in Microsoft has pop-up when path length is long for Excel files

- packaging/distribution/pom.xml
- packaging/distribution/src/main/resources/web-extension-samples/share-config-custom.xml
- share/src/main/resources/alfresco/share-config.xml
- Fixed the problem by having how-authorization-status false by default (share-config.xml) and rely on the share-config-custom.xml that we ship with the dist. zip to override that.
> SHA-2361 : [Community] Can't list users in admin tools

- share-services/src/main/resources/alfresco/templates/webscripts/org/alfresco/slingshot/profile/userprofile.post.json.js
Restrict change of immutable properties in userprofile.post webscript
> MNT-21150 : LDAP synced attributes can be changed using Share

- share/pom.xml
- share/src/main/java/org/alfresco/web/site/servlet/AIMSFilter.java
- share/src/main/java/org/alfresco/web/site/servlet/SSOAuthenticationFilter.java
- share/src/main/java/org/alfresco/web/site/servlet/SlingshotLogoutController.java
- share/src/main/webapp/WEB-INF/keycloak.json
Added ERROR logs if AIMS is not configured correctly.
Set the keycloak configuration to default alfresco realm and Keycloak client.
Updated Keycloak libraries.
> SHA-2372: Added INFO logs on AIMS filter initialization.

- packaging/distribution/src/main/resources/web-extension-samples/share-config-custom.xml
- packaging/docker/src/main/resources/web-extension-samples/share-config-custom.xml
- share/src/main/resources/alfresco/share-config.xml
Moved AIMS configuration from share-config-custom.xml to share-config.xml
> SHA-2443: Moved AIMS configuration

- share/src/main/resources/alfresco/site-webscripts/org/alfresco/components/html.status.ftl
- share/src/main/resources/alfresco/site-webscripts/org/alfresco/errorcode.lib.ftl
- share/src/main/resources/alfresco/site-webscripts/org/alfresco/modules/html.status.ftl
Avoid displaying sensitive information through verbose error messages.
> MNT-20195: Avoid displaying sensitive information

- share/src/main/resources/alfresco/site-webscripts/org/alfresco/components/head/resources.get.html.ftl
- web-framework-commons/src/main/webapp/js/alfresco.js
Remove unreliable document.referrer check with checking if the AIMS is enabled and the status code is 0, in order to refresh the page, when error occurs. 
Improvements on resources template file, so it won't crash when aims.enabled is not configured properly.
> APPS-153: Fix the back button issue.

- pom.xml
Bump webscripts version from 8.6 to 8.7
> APPS-176: Bump webscripts version from 8.6 to 8.7

- pom.xml
- share-encryption/pom.xml
- share-services/pom.xml
- share/pom.xml
- wcmquickstart-module/wcmquickstartclientapi/pom.xml
- wcmquickstart-module/wcmquickstartmodule/pom.xml
- wcmquickstart-module/wcmquickstartwebsite/pom.xml
- web-editor-plugin/pom.xml
- web-editor-samples/customer-site/pom.xml
- web-editor/pom.xml
- web-framework-commons/pom.xml
I update dependencies for a new RC.
> APPS-314: update dependencies in concordance with acs-packaging

- .travis.yml
> APPS-443: Add tests from user group to run in pipeline

- _ci/maven_release.sh
Fix release script by adding git pull to avoid sync issues between local and remote branches
> Fix release script by adding git pull

- pom.xml
> MNT-21922 : Delay spotted when render preview

- pom.xml
- share/src/main/resources/alfresco/share-config.xml
- share/src/main/resources/alfresco/site-webscripts/org/alfresco/components/guest/login.get.html.ftl
- share/src/main/resources/share-config.properties
- share/src/main/webapp/components/guest/login.js
Activation of SAMESITE management in Share 6.2.2. SFDCENG-804: Check SFDC integration compatibility with SameSite=Lax cook…
> cherry pick from 838fea0f8 (SP 6.2.2)

- packaging/distribution/pom.xml
- pom.xml
- share-services/pom.xml
- share/pom.xml
- wcmquickstart-module/wcmquickstartmodule/pom.xml
- web-editor-plugin/pom.xml
- web-editor-samples/customer-site/pom.xml
- web-editor/pom.xml
- web-framework-commons/pom.xml
I update version of : alfresco-core, alfresco-repository and alfresco-remote-api,  with unified version of alfresco-community-repo.
> APPS-598- added unified version.

- share-services/src/main/resources/alfresco/templates/webscripts/org/alfresco/slingshot/documentlibrary/item.lib.ftl
(cherry picked from commit f2cde4e467d2e95fbdc28e7fc93fb0b49e1f7751)
> [MNT-21654] Added validation to check if cm:lastThumbnailModification property exists (6.2.N)

- share-services/src/main/resources/alfresco/templates/webscripts/org/alfresco/slingshot/documentlibrary/item.lib.ftl
(cherry picked from commit f2cde4e467d2e95fbdc28e7fc93fb0b49e1f7751)
> [MNT-21654] Added validation to check if cm:lastThumbnailModification property exists (6.1.N)

- share-services/src/main/resources/alfresco/templates/webscripts/org/alfresco/slingshot/documentlibrary-v2/evaluator.lib.js
- share/src/main/java/org/alfresco/web/scripts/StripLinkedNodePropertiesOption.java
- share/src/main/resources/alfresco/site-webscripts/org/alfresco/components/documentlibrary/data/surf-doclist.get.js
- share/src/main/resources/alfresco/site-webscripts/org/alfresco/components/documentlibrary/data/surf-doclist.lib.js
- share/src/main/resources/alfresco/slingshot-application-context.xml
> MNT-18497 : Displaying Folder With Many Linked Nodes is Slow in Share

- share/pom.xml
The **share/pom.xml** file contains an error which is preventing the project build. 
I have fixed it, however, looking at #325 I would like to be sure that myfaces-impl dependency should continue or not.
> [MNT-21877] Fix pom

- pom.xml
- share/src/main/resources/alfresco/slingshot-application-context.xml
- Additional properties for endpointController bean in slingshot-application-context.xml
- Update Webscripts dependency: 8.12 -> 8.16
- Update Surf dependency: 8.6 -> 8.8
> MNT-22154 : [Security] Share proxy allows unauthenticated access to repository webscripts

- share/src/main/java/org/alfresco/web/scripts/RssDashletStatusWebScript.java
- share/src/main/resources/alfresco/site-webscripts/org/alfresco/components/dashboard/customise-dashlets.get.js
- share/src/main/resources/alfresco/site-webscripts/org/alfresco/components/dashlets/addons.get.html.ftl
- share/src/main/resources/alfresco/site-webscripts/org/alfresco/components/dashlets/addons.get.js
- share/src/main/resources/alfresco/site-webscripts/org/alfresco/components/dashlets/async-rssfeed.get.js
- share/src/main/resources/alfresco/site-webscripts/org/alfresco/components/dashlets/rssfeed.get.html.ftl
- share/src/main/resources/alfresco/site-webscripts/org/alfresco/components/dashlets/rssfeed.get.js
- share/src/main/resources/alfresco/slingshot-application-context.xml
Disable RSS dashlet by default + implement flag to enable it on demand.
The JVM flag will be: `-Drssdashlet.enabled=true`
> MNT-22156 : [Security] Unauthenticated call to internal URLs using RSS feed in Share

- share/src/main/java/org/alfresco/web/site/servlet/AIMSFilter.java
- share/src/main/java/org/alfresco/web/site/servlet/AIMSLogoutController.java
- share/src/main/java/org/alfresco/web/site/servlet/SlingshotLogoutController.java
- share/src/main/resources/alfresco/site-webscripts/org/alfresco/share/imports/share-header.lib.js
- share/src/main/resources/alfresco/slingshot-application-context.xml
- share/src/main/webapp/WEB-INF/web.xml
Switch the single logout from Back-Channel to Front-Channel.
> APPS-596: Switch the logout from Back-Channel to Front-Channel.
