Alfresco/share

packaging/docker/pom.xml
- updated googledocs dependency
=> GOOGLEDOCS-429 : Generate RC2 for GoogleDocs 3.1.0 compatible with ACS Ent 6.0

packaging/docker/docker-compose/docker-compose.yml, packaging/docker/src/main/resources/web-extension-samples/share-config-custom.xml, packaging/docker/substituter.sh, pom.xml
in docker-compose can be set CSRF_FILTER_REFERER and CSRF_FILTER_ORIGIN
substituter.sh makes overrides with those filters if are both set and set CSRFPolicy true otherwise
CSRFPolicy is false and <referer></referer> and <origin></origin> are empty
=> Ace 5842 csrf filter in docker

packaging/docker/pom.xml
- updated googledocs dependency
=> GOOGLEDOCS-437 : Generate Final Build for GoogleDocs 3.1.0 compatible with ACS Ent 6.0

pom.xml
Updated aikau to the latest version.
Sequences like %00 are not present in URLs after the update.
=> Aikau version update

share/src/main/resources/alfresco/site-webscripts/org/alfresco/components/dashlets/colleagues.get.properties
Fixed incorrect label from "Shown the first **n** members" to "Showing the first **n** members"
=> SHA-2199_incorrect_label

share/src/main/java/org/alfresco/web/site/EditionInterceptor.java, share/src/main/java/org/alfresco/web/site/UrlUtil.java, share/src/main/resources/alfresco/site-webscripts/org/alfresco/components/console/application.get.js
Create UrlUtil class which reads the path to Alfresco Share and Alfresco Repository from JVM system properties.
Add UrlUtil object to EditionInterceptor as this "webscript context property" instead of creating a new Interceptor.
Read "repoURL" from context and build the link to admin console (if repoURL != "") else use the old mechanism.
=> REPO-3721 : Admin Console Link Invalid

share/src/main/webapp/components/documentlibrary/toolbar.css, share/src/main/webapp/components/documentlibrary/toolbar.js
If there are lots of either template nodes or folders, when a user tries to create content/folder by these templates, the rendered menus are not scrollable making it difficult to get to a specific item out of the range of the list.
=> MNT-15977 - made create documents by node or folder templates submenu scrollable

web-framework-commons/src/main/webapp/js/alfresco.js
Using more generic error response to the user in the event of un-handled error saving metadata
=> MNT-14338 - using more generic error response to the user when saving metadata

share/src/main/resources/alfresco/enterprise-config.xml
Pls see investigation https://issues.alfresco.com/jira/browse/MNT-16673?focusedCommentId=599641&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-599641
Basically the configuration held in enterprise-config.xml negates any overriding configuration in share-config-custom.xml, this change specifically removes the field length configuration allowing for it to be overridden by the share-config-custom.xml (keeping the auth status display configuration).
=> MNT-16673 - removed overriding Users field length configuration from enterprise-config.xml

pom.xml, share/pom.xml
Please see this comment for investigation and the reason for these changes:
https://issues.alfresco.com/jira/browse/MNT-20234?focusedCommentId=599321&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-599321
Basically created a new patched 'lesscss-engine' and pulling that in, also removing the possibility of pulling in duplicate library via spring-surf
=> MNT-20234 - (re) patched lesscss-engine and pulling in new dependency

packaging/docker/.maven-dockerignore, packaging/docker/pom.xml, packaging/pom.xml
First part of *ATS-345*:
- add `fabric8-maven-plugin` configurations for building and publishing the base `quay.io/alfresco-share` image
- add 3 separate profiles for different scenarios
- build local docker image (`local` profile)
- build & push docker image (`internal` profile, for the CI tool)
- build & push the release docker image (`release` profile, also for the CI tool)
:warning: These changes are inactive at the moment, as the build plan wasn't yet changed. Once we have a green build, I'll activate the new Maven profiles.
:warning: When we'll merge these changes into the `master` branch, we'll also cherry-pick the commit into `support/SP/6.1.N`, `support/HF/6.1.0`, `support/SP/6.0.N` and `support/HF/6.0.1`.
=> ATS-345 : Build and push Share Docker images with Maven

packaging/docker-aws/.maven-dockerignore, packaging/docker-aws/Dockerfile, packaging/docker-aws/pom.xml, packaging/pom.xml
Second part of _ATS-345_:
- add new `packaging/docker-aws` directory and maven module for building and publishing the **quay.io/alfresco/alfresco-share-aws** docker image, which at the moment contains the **alfresco-ai-share** amp on top of the base **alfresco/alfresco-share** image
- add 3 separated build profiles, the same ones used by the `packaging/docker` module: _local_, _internal_ and _release_
:warning: Once we merge these changes into the `master` branch, we'll also cherry-pick them into `support/SP/6.1.N` and `support/HF/6.1.0`. Older Alfresco versions can't use the AI features.
=> ATS-345 : Build and publish custom *alfresco-share-aws* Docker image

packaging/docker-aws/pom.xml
This change will be cherry-picked into the branches:
- **support/SP/6.1.N**
_and_
- **suport/HF/6.1.0**.
However, no new HF/SP are planned for this change only - we'll only check that the regular builds are still green.
=> ATS-384 : Update AI amp version to 1.0.1

pom.xml
Updated the Apache CXF dependencies from 3.0.10 to 3.1.14 in order to fix security vulnerabilities.
=> MNT-20520: Update Apache CXF dependencies from 3.0.10 to 3.1.14

share/src/main/resources/alfresco/share-config.xml
Following the fix that went into MNT-20399, it meant that the auth status columns in the users listing in Share was set to no show by default - this small change puts that right.
This was as discussed in a Share triage call on Monday 8th July 2019
=> MNT-20723 - small change to make authorization status columns appear by default for users

pom.xml
Fix for vulnerabilities:
CVE-2018-14721
CVE-2018-14718
CVE-2018-14719
CVE-2018-19360
CVE-2018-19361
CVE-2018-19362
CVE-2019-14379
CVE-2019-14540
CVE-2019-16335
CVE-2019-16942
CVE-2019-16943
CVE-2019-17531
CVE-2019-17267
CVE-2018-5968
CVE-2018-12022
CVE-2018-12023
CVE-2019-12086
CVE-2019-14439
=> Added dependency management for jackson libraries (v2.10.2)

packaging/docker-aws/pom.xml
=> ATS-651 : AIS: Release Intelligence Services 1.1.2 (compatible with ACS 6.2.0)

pom.xml, share/pom.xml, share/src/main/resources/alfresco/web-extension/custom-slingshot-application-context.xml.sample
Provided new config section https://docs.hazelcast.org/docs/3.11/manual/html-single/index.html#untrusted-deserialization-protection
=> Bumped hazelcast to version 2.4-20200303-alfresco-patched

packaging/docker/pom.xml
=> GOOGLEDOCS-497: Updated pom.xml file to use 'GoogleDocs 3.2.0-RC3' (cherry-picked from master)

share-services/pom.xml
to avoid the -force option of the alfresco-mmt.jar
=> ACS-120 - Removed commons-lang that is being brought in transitively in alfresco-remote-api

share-services/src/main/resources/alfresco/templates/webscripts/org/alfresco/collaboration/tagQuery.get.js
I have added a new clause as described in issue, however, I would like to confirm the query that is being built is correct.
Example of query:
`PATH:"/app:company_home/app:shared//*"
AND ASPECT:{http://www.alfresco.org/model/content/1.0}taggable
-ASPECT:{http://www.alfresco.org/model/content/1.0}workingcopy
AND ISNOTNULL:{http://www.alfresco.org/model/content/1.0}taggable`
My question is, shouldn't exist an AND operator in the third clause? I'm getting more results than I would expect comparing with the same query using the AND operator. Just want to be sure I'm not missing something here.
=> [MNT-20091] Added check to filter cm:taggable aspect with null

share/src/main/resources/alfresco/slingshot-documentlibrary-context.xml, share/src/main/webapp/components/documentlibrary/actions.js
It has been decided not to include these changes (rtf, visio) in master and 6.2.N code line, reverting them for now. They've been added to 5.2.7 and 5.2.N.
=> MNT-18448 MNT-19466: Reverting RTF and Visio extensions

share/src/main/java/org/alfresco/web/site/servlet/config/AIMSConfig.java, share/src/main/resources/share-config.properties, share/src/test/java/org/alfresco/web/config/properties/AIMSConfigTest.java, share/src/test/resources/alfresco/module/shareProperties/share-config.properties
Make sure that sslRequired won't be set with an invalid value
Prepared the AIMSConfig for the rest of the Keycloack configurable values.
Set share config.properties file to default Keycloack values.
Added more unit tests.
=> APPS-212: Make sure that sslRequired won't be set with an invalid value

share/src/main/java/org/alfresco/web/site/servlet/AIMSFilter.java, share/src/main/webapp/WEB-INF/web.xml
`this.loginController.beforeSuccess(request, response)` puts in session the **_alf_USER_GROUPS** attribute which contains the groups that the user logged in is a member of.
I discovered that `this.initUser(request)` from AIMSFilter after many debug steps invokes `loadUser` from SlingshotUserFactory which looks in the session for **_alf_USER_GROUPS** attribute and sets the value of it as a property of the logged in user called **alfUserGroups**. This property is used in WebScripts using `user.properties["alfUserGroups"].split(,)` to get an array of the groups that the user is a member of. 
*Current behaviour*:  `this.initUser(request)` from AIMSFilter is looking for **_alf_USER_GROUPS** which is null and then `this.loginController.beforeSuccess(request, response)` puts in session the …
=> SFDCENG-850: Fix for Salesforce

packaging/docker-aws/pom.xml
- AIS service pack - targeting ACS 6.2.2 (as part of S/H release train)
=> ATS-808: Bump AIS to 1.2.1-RC2

_ci/execute_share_web.sh
APPS-410: Fixed the "failed tests, green build", by returning the exit code from the mvn background process.
=> APPS-410: Failed tests, green build

share-services/src/main/resources/alfresco/templates/webscripts/org/alfresco/slingshot/documentlibrary/item.lib.ftl
Prevents an error to happen if for some reason there are nodes without the property cm:lastThumbnailModification, making the "My Documents" dashlet listing these nodes.
=> [MNT-21654] Added validation to check if cm:lastThumbnailModification property exists

share/src/main/resources/alfresco/site-webscripts/org/alfresco/share/imports/share-header.lib.js
The change in here introduce a new method to read from the manifest file in share service the same version used in share in order to have an aligned comparision between versions. This warning raised after fixing the versioning in share service.
=> Resolving the problem of the warning claiming the same version between share and share services

.travis.yml
Because of license expiration in January 2021, is required to stop using whitesource code scan.
In order to continue to receive feedback from tests stage we need to temporarily commented this job.
=> feature/APPS-758: Temporarily disabled white source travis job
